import { strict as assert } from "node:assert";
import { readFile } from "node:fs/promises";
import Module from "node:module";
import { test } from "node:test";
import vm from "node:vm";
import ts from "typescript";

async function importRouteWithMocks(mocks, cacheKey) {
  const source = await readFile(
    new URL("../../../app/api/lusie/runs/[runId]/download/stl/route.ts", import.meta.url),
    "utf8"
  );
  const { outputText } = ts.transpileModule(source, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      esModuleInterop: true,
    },
  });

  const exports = {};
  const module = { exports };
  const baseRequire = Module.createRequire(import.meta.url);
  const requireWithMocks = (specifier) => specifier in mocks ? mocks[specifier] : baseRequire(specifier);
  const script = new vm.Script(outputText, { filename: `stl-route.${cacheKey}.cjs` });
  const context = vm.createContext({
    Buffer,
    Response,
    URL,
    exports,
    module,
    require: requireWithMocks,
  });

  script.runInContext(context);
  return module.exports;
}

test("STL download returns local generated bytes instead of redirecting to the remote Tripo URL", async () => {
  const localBytes = Buffer.from("solid local-stl");
  const readFileCalls = [];
  const route = await importRouteWithMocks(
    {
      "node:fs/promises": {
        readFile: async (filePath) => {
          readFileCalls.push(String(filePath));
          return localBytes;
        },
      },
      "@/lib/lusie/server/storage": {
        getRunDir: (runId) => `runs/${runId}`,
        loadRun: async (runId) => ({
          runId,
          status: "Ready",
          files: {
            stl: `/api/lusie/runs/${runId}/download/stl`,
            stlSourceUrl: "https://tripo.example/model.stl",
          },
        }),
      },
    },
    `local-${Date.now()}`
  );

  const response = await route.GET(new Request("http://localhost/api/lusie/runs/run-1/download/stl"), {
    params: Promise.resolve({ runId: "run-1" }),
  });

  assert.equal(response.status, 200);
  assert.equal(response.headers.get("Content-Type"), "model/stl");
  assert.equal(response.headers.get("Location"), null);
  assert.equal(await response.text(), localBytes.toString());
  assert.equal(readFileCalls.length, 1);
  assert.ok(readFileCalls[0].endsWith("runs\\run-1\\model.stl") || readFileCalls[0].endsWith("runs/run-1/model.stl"));
});
